import { DefaultTheme, defineConfig } from "vitepress";
import { groupIconMdPlugin, groupIconVitePlugin } from 'vitepress-plugin-group-icons'
import AutoNav from "vite-plugin-vitepress-auto-nav";
import { execSync } from "node:child_process";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  // base: '/Docs/',
  title: "Hypo的文档站",
  description: ".",
  srcDir: 'docs',
  cleanUrls: true,
  lastUpdated: true,
  async transformPageData(pageData, { siteConfig }) {
    if (pageData.frontmatter.layout === 'home') return

    // 1. Get Git Created Time
    if (!pageData.frontmatter.date) {
      try {
        const file = pageData.filePath
        const stdout = execSync(`git log --diff-filter=A --format=%at -1 -- "${file}"`).toString()
        if (stdout) {
          pageData.frontmatter.date = new Date(parseInt(stdout) * 1000)
        }
      } catch (e) {
        // Silent failure in non-git envs
      }
    }

    // 2. Count Words
    const content = pageData.content || ''
    const pattern = /[a-zA-Z0-9_\u00A0-\u02AF\u0392-\u03c9\u0410-\u04F9]+|[\u4E00-\u9FFF\u3400-\u4dbf\uf900-\ufaff\u3040-\u309f\uac00-\ud7af]+/g
    const m = content.match(pattern)
    let count = 0
    if (m) {
      for (let i = 0; i < m.length; i++) {
        if (m[i].charCodeAt(0) >= 0x4e00) {
          count += m[i].length
        } else {
          count += 1
        }
      }
    }
    pageData.frontmatter.wordCount = count
  },
  markdown: {
    lineNumbers: true,
    math: true,
    config(md) {
      md.use(groupIconMdPlugin)
    }
  },
  vite: {
    plugins: [
      groupIconVitePlugin(),
      AutoNav({
        // Custom configuration can be added here
        // For now, we use defaults which respect srcDir/srcExclude
      })
    ]
  },
  head: [["link", { rel: "icon", href: "/logo.svg" }]],
  themeConfig: {
    outlineTitle: "目录",
    outline: [2, 6],
    docFooter: {
      prev: "上一篇",
      next: "下一篇",
    },
    // aside: "left", // 设置右侧侧边栏在左侧显示
    logo: "public/logo.svg",
    // https://vitepress.dev/reference/default-theme-config
    // nav removed - generated by AutoNav
    // 上次更新样式
    lastUpdated: {
      text: "最后更新于",
      formatOptions: {
        dateStyle: "long",
        timeStyle: "medium",
      },
    },

    search: {
      provider: "local",
      options: {
        translations: {
          button: {
            buttonText: "搜索文档",
            buttonAriaLabel: "搜索文档",
          },
          modal: {
            noResultsText: "无法找到相关文档",
            resetButtonTitle: "清除查询条件",
            footer: {
              selectText: "选择",
              navigateText: "切换",
            },
          },
        },
      },
    },
    // sidebar removed - generated by AutoNav
    footer: {
      copyright: "Copyright © 2023 Hypo",
    },
    socialLinks: [{ icon: "github", link: "https://github.com/Theproudcold" }],
  },
});
